### PR TITLE
Add support to 2024.2, still incomplete*

### PR DESCRIPTION
**Pull request by miguelmagueijo**
**Adds support to 2024.2.* versions;**

This PR still has deprecation problems related to Favorite classes that show errors on IDE startup.
- FavoritesManager (`com.intellij.ide.favoritesTreeView.FavoritesManager`);

### Changes made to fix deprecation of certain classes or methods:
- `com.intellij.openapi.util.io.UniqueNameBuilder` -> `com.intellij.filename.UniqueNameBuilder`;
- `org.apache.commons.lang.StringUtils` -> `org.apache.commons.lang3.StringUtils`;
- `com.intellij.ui.JBColor` -> `com.intellij.util.ui.UIUtil`;
- `com.intellij.ui.ColorChooser` -> `com.intellij.ui.ColorChooserService`;
- Remove use of `IconDeferrer`, manually check if icons are equal;
- `ActionUtil.performActionDumbAware(myAction, event)` -> `ActionUtil.performActionDumbAwareWithCallbacks(myAction, event)`

### CODE REVIEW

**Comment by julianpoemp** [comment]
@krasa the plugin is not working any more with the latest version of the IDE. Can you please merge and release this PR?

**Comment by julianpoemp** [comment]
I built the PR and it's working fine on MacOS ARM with the latest version of PHPStorm

**Comment by krasa** [comment]
It seems that it is being worked on at https://github.com/mallowigi/EditorGroups

**Comment by krasa** [comment]
My repo is not actual, mallowigi relesed the last version 2.0. We should probably use a single repo.

**Comment by krasa** [comment]
Sorry for the mess, mallowigi ported it to 2024.2 but can't release it as it still contains deprecated api. 
The whole favorites must be replaced afaik.

This repo will not be used. I will not archive it atm for the sake of discussion.

**Comment by julianpoemp** [comment]
@krasa it would already help us a lot if you could just publish the changes from this PR  without merging the changes from the other fork. The version from the other fork is not published to the marketplace, so your version is more important.

**Comment by krasa** [comment]
Actually his version is the last one published - he has rights to do it and continues with the development. I am surprised mine even works.

**Comment by julianpoemp** [comment]
@krasa thank you for your answers. I didn't know that the other fork has published a 2.0 version and thought you are the only one to publish updates. Version 2.0 isn't working with the latest version of the IDE, but that's an issue on the other fork.

Thank you for your work and have a nice day!

**Comment by mallowigi** [comment]
@julianpoemp I had already implemented your changes in the `deprecate` branch of my fork, besides a few differences.

I encourage you to push changes to that branch as this includes the last updated version.

Unfortunately, as Vojtech said, the plugin cannot be released until we manage to remove all deprecated and experimental APIs. But you can still build for yourself

**Comment by julianpoemp** [comment]
@mallowigi I didn't create the changes, they are made by @miguelmagueijo. I just found this PR and because it fixes the compatibility issue, I asked @krasa if it can be merged :)

Because this repository is not maintained any more, could you enable issue tracking on your fork? That way people have a chance to report bugs and contribute :)

**Comment by mallowigi** [comment]
Sure, but be aware that I am also a tad busy to have time working on this plugin myself, so this will be on you guys if you want to fix the plugin to be ready for release :)

**Comment by krasa** [comment]
> Unfortunately, as Vojtech said, the plugin cannot be released until we manage to remove all deprecated and experimental APIs. But you can still build for yourself

Well, technically it can be. I never had a problem with it. Or someone said something to you?

**Comment by krasa** [comment]
I would rather like to see some error handling, when API changes. The result of that was not very nice the last time. UI was broken, some try catches would prevent it.

**Comment by mallowigi** [comment]
The JetBrains folks reject anything that is using internal api. But since you released it some time ago they might let you off. But the favorites api is in deprecation and unless we replace it or remove it, it won't last long.

Id love if I had the time to work on it and also convert it to kotlin

**Comment by miguelmagueijo** [comment]
Sorry for being MIA. @mallowigi do you need anything from my changes? I've seen you fixed the colors deprecation warning, but is it the rest already fixed?
I don't know if you already tested on 2024.2.* versions but the component is too small, I've yet to discover how to make it bigger and probably add a setting to control the size. From now on, more changes should I make open PRs to your repo?

**Comment by mallowigi** [comment]
Yes please, like I said elsewhere the plugin cannot be sent to the marketplace until we remove all deprecated and internal code...

**Comment by miguelmagueijo** [comment]
I've already compared my changes with your `deprecate` branch and you seem to have it all. The only thing missing is upping the version of the `pluginUntilBuild` to 2024.2. Thus I won't open a new PR.

**Pull request merged**
